{
  "formatVersion": "1.1",
  "component": {
    "group": "net.crypticverse.secret",
    "module": "BetterBiomes-Secret",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "BetterBiomes-Secret-1.0.1.jar",
          "url": "BetterBiomes-Secret-1.0.1.jar",
          "size": 8438,
          "sha512": "8cbb70ec506c23c77fedc21cbfaff0cc0d714b56410355166f9294d4eaabeee58c7a4404147248b2c2579bc294d0d5424058200c80a62366b06bf6e73bb59676",
          "sha256": "10b0379a939213386753d019e6c18fc170144d5e6d1d203bd5321ac03d0a0e42",
          "sha1": "2bffd76870e1d1d29bfc5e31b59993ed7b4eebf9",
          "md5": "2287e4f0c546052877f085bff8ae3639"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.91.3+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "BetterBiomes-Secret-1.0.1.jar",
          "url": "BetterBiomes-Secret-1.0.1.jar",
          "size": 8438,
          "sha512": "8cbb70ec506c23c77fedc21cbfaff0cc0d714b56410355166f9294d4eaabeee58c7a4404147248b2c2579bc294d0d5424058200c80a62366b06bf6e73bb59676",
          "sha256": "10b0379a939213386753d019e6c18fc170144d5e6d1d203bd5321ac03d0a0e42",
          "sha1": "2bffd76870e1d1d29bfc5e31b59993ed7b4eebf9",
          "md5": "2287e4f0c546052877f085bff8ae3639"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BetterBiomes-Secret-1.0.1-sources.jar",
          "url": "BetterBiomes-Secret-1.0.1-sources.jar",
          "size": 5340,
          "sha512": "c9d35ac8338753be1f69c6bfbb5f8b5b2e5f75006b82a58db723b59b3bf4803a3f04e2865d789858e3df74131810450708f33f39e27ac31b3356970d0aa8724a",
          "sha256": "173c2c8159001a2dcdadaea5ac09365b1afa5359e49526707b59506bb6588d46",
          "sha1": "0404a86067f93f12c45e4ab5ccdab6dfe9812b5d",
          "md5": "257688d88799e11e8341bdca108d98c7"
        }
      ]
    }
  ]
}
