{
  "formatVersion": "1.1",
  "component": {
    "group": "net.crypticverse.betterbiomes",
    "module": "BetterBiomes-Fabric",
    "version": "2.1.4.3-1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "13.0.121"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "11.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "BetterBiomes-Fabric-2.1.4.3-1.20.4.jar",
          "url": "BetterBiomes-Fabric-2.1.4.3-1.20.4.jar",
          "size": 2668261,
          "sha512": "11dee8baeded0701dc21e796d2fa6394e53a664301c11021c74eda99e474ab40b0d5c521b85b5dc301a472ed6bc5ca3d3da13333432a38b0161c74bae822216b",
          "sha256": "d9f5b40f848cf1aa4ab6bae74525a5158eb28fa83a3ecaab5256f6542e1b7d78",
          "sha1": "8faca4c771893bec865d3f279cdbd996b51c8ed6",
          "md5": "a473a158361f4e0f4d66b0d2400a624e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "13.0.121"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "11.0.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.94.1+1.20.4"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.4-3.3.0.10"
          }
        },
        {
          "group": "com.terraformersmc.terraform-api",
          "module": "terraform-wood-api-v1",
          "version": {
            "requires": "9.0.0"
          }
        },
        {
          "group": "net.crypticverse.secret",
          "module": "BetterBiomes-Secret",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "14.0.688"
          }
        }
      ],
      "files": [
        {
          "name": "BetterBiomes-Fabric-2.1.4.3-1.20.4.jar",
          "url": "BetterBiomes-Fabric-2.1.4.3-1.20.4.jar",
          "size": 2668261,
          "sha512": "11dee8baeded0701dc21e796d2fa6394e53a664301c11021c74eda99e474ab40b0d5c521b85b5dc301a472ed6bc5ca3d3da13333432a38b0161c74bae822216b",
          "sha256": "d9f5b40f848cf1aa4ab6bae74525a5158eb28fa83a3ecaab5256f6542e1b7d78",
          "sha1": "8faca4c771893bec865d3f279cdbd996b51c8ed6",
          "md5": "a473a158361f4e0f4d66b0d2400a624e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BetterBiomes-Fabric-2.1.4.3-1.20.4-sources.jar",
          "url": "BetterBiomes-Fabric-2.1.4.3-1.20.4-sources.jar",
          "size": 168411,
          "sha512": "668ae0bf1a6d21ce7503c2d0b729a1074e636157998a84eaf4101042858aaf6b6c2256134ff9fa8c5382e77abb7430f5cb6cbe51298f9b413ec8ed61399e716f",
          "sha256": "e8d8312d27f513fdcff50606a18dd8f6a625b4aae20b86b3dd9b5869b3082e07",
          "sha1": "a7f3b8748b26131e98650c72998a37e6ff175a2d",
          "md5": "5680913f7204913d002b2159c6507a48"
        }
      ]
    }
  ]
}
