{
  "formatVersion": "1.1",
  "component": {
    "group": "net.crypticverse.betterbiomes",
    "module": "BetterBiomes-Fabric",
    "version": "2.1.4.6-1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "13.0.121"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "11.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "BetterBiomes-Fabric-2.1.4.6-1.20.4.jar",
          "url": "BetterBiomes-Fabric-2.1.4.6-1.20.4.jar",
          "size": 2810300,
          "sha512": "f30b9838ff2eb8607043429f1dc4eaf9ad4c798a8d83203b7092ab6eda5a8eee9d723ddd18836ba1fb56fbdb60b5a00c3e89c20777cf7fa75cd79edae22c4459",
          "sha256": "e8944bb83c02a07f2c062266afa3edf84d0ba39198025ff96ff10312b7dc8a73",
          "sha1": "c5f2d6dce5a750a6047f513c10c2ab8910703f18",
          "md5": "b73d6e9cd144c90a72de3c01568e95a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "13.0.121"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "11.0.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.0+1.20.4"
          }
        },
        {
          "group": "dev.bookkeepersmc",
          "module": "Notebook-api-fabric-1.20.4",
          "version": {
            "requires": "1.0.0.2"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.4-3.3.0.12"
          }
        },
        {
          "group": "com.terraformersmc.terraform-api",
          "module": "terraform-wood-api-v1",
          "version": {
            "requires": "9.0.0"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "14.0.688"
          }
        }
      ],
      "files": [
        {
          "name": "BetterBiomes-Fabric-2.1.4.6-1.20.4.jar",
          "url": "BetterBiomes-Fabric-2.1.4.6-1.20.4.jar",
          "size": 2810300,
          "sha512": "f30b9838ff2eb8607043429f1dc4eaf9ad4c798a8d83203b7092ab6eda5a8eee9d723ddd18836ba1fb56fbdb60b5a00c3e89c20777cf7fa75cd79edae22c4459",
          "sha256": "e8944bb83c02a07f2c062266afa3edf84d0ba39198025ff96ff10312b7dc8a73",
          "sha1": "c5f2d6dce5a750a6047f513c10c2ab8910703f18",
          "md5": "b73d6e9cd144c90a72de3c01568e95a9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BetterBiomes-Fabric-2.1.4.6-1.20.4-sources.jar",
          "url": "BetterBiomes-Fabric-2.1.4.6-1.20.4-sources.jar",
          "size": 234168,
          "sha512": "99bc5e0ca76ff9d9f39f2e8a0b39116ca37645c2d94db463ccbbe4d84f5fd9e026b9920ba857c7452b447f5ea07ae04706c66f2e7b1cdc5dfd6f3a6e2b1188ec",
          "sha256": "fb1205ce5a53eeb5ddbfa1b1e34ecc94edf0cc00ce389a6de3cc5d7e7d230c39",
          "sha1": "e39bd9ea3edd85bce35b583a3b84d467345a99ff",
          "md5": "09ac60084607f3ebaa9542488f41572e"
        }
      ]
    }
  ]
}
