{
  "formatVersion": "1.1",
  "component": {
    "group": "net.crypticverse.betterbiomes",
    "module": "BetterBiomes-Fabric",
    "version": "1.1.3.3-1.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "BetterBiomes-Fabric-1.1.3.3-1.20.2.jar",
          "url": "BetterBiomes-Fabric-1.1.3.3-1.20.2.jar",
          "size": 2769652,
          "sha512": "1bc40846a1e8cc87ccc6778da2db594d55961603c2e3e048de4e4bfea21a2c0563003837c7eecb1d95c62fa53258a51b0cffc36b17946e6b00fd408b42ddc26d",
          "sha256": "9217abf3feb5873036287c38177707265f43a06b4524e0b856b4c9671c36366b",
          "sha1": "615455a8add7407e70af9d586018660fe7cca009",
          "md5": "4d1f1a26fb754cf82901e6b43d7452fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.91.2+1.20.2"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.2-3.2.0.14"
          }
        },
        {
          "group": "com.terraformersmc.terraform-api",
          "module": "terraform-wood-api-v1",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "13.0.671"
          }
        }
      ],
      "files": [
        {
          "name": "BetterBiomes-Fabric-1.1.3.3-1.20.2.jar",
          "url": "BetterBiomes-Fabric-1.1.3.3-1.20.2.jar",
          "size": 2769652,
          "sha512": "1bc40846a1e8cc87ccc6778da2db594d55961603c2e3e048de4e4bfea21a2c0563003837c7eecb1d95c62fa53258a51b0cffc36b17946e6b00fd408b42ddc26d",
          "sha256": "9217abf3feb5873036287c38177707265f43a06b4524e0b856b4c9671c36366b",
          "sha1": "615455a8add7407e70af9d586018660fe7cca009",
          "md5": "4d1f1a26fb754cf82901e6b43d7452fd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BetterBiomes-Fabric-1.1.3.3-1.20.2-sources.jar",
          "url": "BetterBiomes-Fabric-1.1.3.3-1.20.2-sources.jar",
          "size": 163284,
          "sha512": "aa214054edbafff6b32dca1861359f031325a035e3cb8a1c3420aca73da3267baf2e591ef335ef4680c34256389d7fe90a9c8489e30a688e66fefb898df2c580",
          "sha256": "37818beefb9a206ecd098bc7f06e31ded9c2414019592859ac6170506282721d",
          "sha1": "c00a55e50a546c961e63db144509f15bf3303993",
          "md5": "592bf21a6bde6af4d3917ce08104cc73"
        }
      ]
    }
  ]
}
