{
  "formatVersion": "1.1",
  "component": {
    "group": "net.crypticverse.betterbiomes",
    "module": "BetterBiomes-Fabric",
    "version": "1.1.4.5-1.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "12.0.119"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "10.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "BetterBiomes-Fabric-1.1.4.5-1.20.2.jar",
          "url": "BetterBiomes-Fabric-1.1.4.5-1.20.2.jar",
          "size": 2860991,
          "sha512": "c1b86e05707c57031bd5730d6ca30774e1677241b6bb57f683e4fe56798567690653e194ce7a28d3a1dd0b479d8af205e205a29c8ed173e06c456060eb997489",
          "sha256": "aef02ca74e165d7e06ca6e643b54823d4a9b9a4c3d4e23766294cd92cb87a9fa",
          "sha1": "d0e8ca4d195df764e91570b843e0ede963a5b456",
          "md5": "b56e08b65c5dc3dc95c940cc27e3d261"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "12.0.119"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "10.0.17"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.91.4+1.20.2"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.2-3.2.0.14"
          }
        },
        {
          "group": "com.terraformersmc.terraform-api",
          "module": "terraform-wood-api-v1",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "13.0.685"
          }
        }
      ],
      "files": [
        {
          "name": "BetterBiomes-Fabric-1.1.4.5-1.20.2.jar",
          "url": "BetterBiomes-Fabric-1.1.4.5-1.20.2.jar",
          "size": 2860991,
          "sha512": "c1b86e05707c57031bd5730d6ca30774e1677241b6bb57f683e4fe56798567690653e194ce7a28d3a1dd0b479d8af205e205a29c8ed173e06c456060eb997489",
          "sha256": "aef02ca74e165d7e06ca6e643b54823d4a9b9a4c3d4e23766294cd92cb87a9fa",
          "sha1": "d0e8ca4d195df764e91570b843e0ede963a5b456",
          "md5": "b56e08b65c5dc3dc95c940cc27e3d261"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BetterBiomes-Fabric-1.1.4.5-1.20.2-sources.jar",
          "url": "BetterBiomes-Fabric-1.1.4.5-1.20.2-sources.jar",
          "size": 236943,
          "sha512": "ce7f359d8d8dd8430f1ce36b1b162d5ae72044fc8edf70d9845c55a6e0587f66dad12a8f98c5f12edbfc9e1cc5ef90f90db32e462c0ebb0e17cc33f62b277ee8",
          "sha256": "3d64b3320e931392de6f9da1ddff74b3c4eb16b4ede1df75b52907fecdf87073",
          "sha1": "2b013e492b8b99e2a642898f4c5f9856ec556cd6",
          "md5": "a8f2cc345098e79039229d9b6fd679af"
        }
      ]
    }
  ]
}
