{
  "formatVersion": "1.1",
  "component": {
    "group": "net.crypticverse.betterbiomes",
    "module": "BetterBiomes-Fabric",
    "version": "2.1.4.2-1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "13.0.121"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "11.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "BetterBiomes-Fabric-2.1.4.2-1.20.4.jar",
          "url": "BetterBiomes-Fabric-2.1.4.2-1.20.4.jar",
          "size": 2668758,
          "sha512": "9dffc4509edc012a95816e4e3443c6de7ee594dc7a90ac0616e0811ef2e33b70ac45f61c3b3b15fc1f3a3207b5f1b94f93c103b92c6bb0a1ad5506b011ce2b47",
          "sha256": "8147d2ebf7c807d34d3f05337cecc499e1f7f716d08af34d33b566351c4fe998",
          "sha1": "0f3f7e4a6f188a9f71584ed2506d7bd24a4ff0dd",
          "md5": "605960ba2e07a717e2891707ac70e811"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "13.0.121"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "11.0.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.94.0+1.20.4"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.4-3.3.0.10"
          }
        },
        {
          "group": "com.terraformersmc.terraform-api",
          "module": "terraform-wood-api-v1",
          "version": {
            "requires": "9.0.0"
          }
        },
        {
          "group": "net.crypticverse.secret",
          "module": "BetterBiomes-Secret",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "14.0.688"
          }
        }
      ],
      "files": [
        {
          "name": "BetterBiomes-Fabric-2.1.4.2-1.20.4.jar",
          "url": "BetterBiomes-Fabric-2.1.4.2-1.20.4.jar",
          "size": 2668758,
          "sha512": "9dffc4509edc012a95816e4e3443c6de7ee594dc7a90ac0616e0811ef2e33b70ac45f61c3b3b15fc1f3a3207b5f1b94f93c103b92c6bb0a1ad5506b011ce2b47",
          "sha256": "8147d2ebf7c807d34d3f05337cecc499e1f7f716d08af34d33b566351c4fe998",
          "sha1": "0f3f7e4a6f188a9f71584ed2506d7bd24a4ff0dd",
          "md5": "605960ba2e07a717e2891707ac70e811"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BetterBiomes-Fabric-2.1.4.2-1.20.4-sources.jar",
          "url": "BetterBiomes-Fabric-2.1.4.2-1.20.4-sources.jar",
          "size": 168409,
          "sha512": "6a8ab43bfa33e0a17be0f919a7d7e4d9fc03187bd659b7c607e24f0429c0efe5b524744969b0f25706f941bf4e4365f3aa167f4c44db78d730f730b8da3dd22c",
          "sha256": "a4c1dd47f976c05a3101f0e78f86fbbf50ecd5c9cabcdb656e1bc01ec9745289",
          "sha1": "516a99bd9c5d8cdc2c5f96575d08e45f5fe3b71a",
          "md5": "faf650d9ed64c85850b001f3e7517302"
        }
      ]
    }
  ]
}
