{
  "formatVersion": "1.1",
  "component": {
    "group": "net.crypticverse.betterbiomes",
    "module": "BetterBiomes-Fabric",
    "version": "2.1.4.7-1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "13.0.121"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "11.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "BetterBiomes-Fabric-2.1.4.7-1.20.4.jar",
          "url": "BetterBiomes-Fabric-2.1.4.7-1.20.4.jar",
          "size": 2884036,
          "sha512": "0a7b9657b046648842f36bbb7b73c1aea250d8dbe303f515d6c4a5c0b0c11231d56aea524a492acf2a69bd4b69a60e84f136d257a43780eaea040514b8c6e5e1",
          "sha256": "28a617462b45a1e04fec3fb4e59c55194f35bc0654ac98f56496942ec742c3e0",
          "sha1": "95e82c2ee9d0e8b0f7d454bcfbf51422cc358f72",
          "md5": "fad88ff27a86da7b3181fd8faba3b69d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "13.0.121"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "11.0.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "com.bookkeepersmc",
          "module": "Notebook-api-fabric-1.20.4",
          "version": {
            "requires": "1.1.8+1.20.4"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.4-3.3.0.12"
          }
        },
        {
          "group": "com.terraformersmc.terraform-api",
          "module": "terraform-wood-api-v1",
          "version": {
            "requires": "9.0.0"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "14.0.688"
          }
        }
      ],
      "files": [
        {
          "name": "BetterBiomes-Fabric-2.1.4.7-1.20.4.jar",
          "url": "BetterBiomes-Fabric-2.1.4.7-1.20.4.jar",
          "size": 2884036,
          "sha512": "0a7b9657b046648842f36bbb7b73c1aea250d8dbe303f515d6c4a5c0b0c11231d56aea524a492acf2a69bd4b69a60e84f136d257a43780eaea040514b8c6e5e1",
          "sha256": "28a617462b45a1e04fec3fb4e59c55194f35bc0654ac98f56496942ec742c3e0",
          "sha1": "95e82c2ee9d0e8b0f7d454bcfbf51422cc358f72",
          "md5": "fad88ff27a86da7b3181fd8faba3b69d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BetterBiomes-Fabric-2.1.4.7-1.20.4-sources.jar",
          "url": "BetterBiomes-Fabric-2.1.4.7-1.20.4-sources.jar",
          "size": 234209,
          "sha512": "552a748806fa83aa0a5dc4efb66eda686d9ff1276d7003000564153d4a662830744c0e3726b7de9ed6449cdd63fb7136fb1cda1070417282ce0a39650befc4a0",
          "sha256": "27e993ae6f0874a0b7075dc5132b61511c90cefd3a186714e0c60e676d7d35d4",
          "sha1": "52c0e28a436e264f6ab052960eeabc564d62e2ce",
          "md5": "8c1d7ecce4ec985947610b0c7e42802d"
        }
      ]
    }
  ]
}
