{
  "formatVersion": "1.1",
  "component": {
    "group": "net.crypticverse.betterbiomes",
    "module": "BetterBiomes-Fabric",
    "version": "1.1.4.3-1.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "12.0.119"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "10.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "BetterBiomes-Fabric-1.1.4.3-1.20.2.jar",
          "url": "BetterBiomes-Fabric-1.1.4.3-1.20.2.jar",
          "size": 2793186,
          "sha512": "d8671d96c7cacca242af87065fb241ed7a652a8fa8044817f200a69fab798f6492456e01b307bb56f140b64cf99f359181877b1ee455c6f61c634047fe689671",
          "sha256": "f8b95406e0a02e8e3cbb318688c491bb2f2381f375cad8fc252650c003738835",
          "sha1": "535877fb36bc6ab5810073d153b37f1ed86fd4b3",
          "md5": "1c9e99f8eea6e41e8eedbd4e01dd22f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "12.0.119"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "10.0.17"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.91.4+1.20.2"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.2-3.2.0.14"
          }
        },
        {
          "group": "com.terraformersmc.terraform-api",
          "module": "terraform-wood-api-v1",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "13.0.685"
          }
        }
      ],
      "files": [
        {
          "name": "BetterBiomes-Fabric-1.1.4.3-1.20.2.jar",
          "url": "BetterBiomes-Fabric-1.1.4.3-1.20.2.jar",
          "size": 2793186,
          "sha512": "d8671d96c7cacca242af87065fb241ed7a652a8fa8044817f200a69fab798f6492456e01b307bb56f140b64cf99f359181877b1ee455c6f61c634047fe689671",
          "sha256": "f8b95406e0a02e8e3cbb318688c491bb2f2381f375cad8fc252650c003738835",
          "sha1": "535877fb36bc6ab5810073d153b37f1ed86fd4b3",
          "md5": "1c9e99f8eea6e41e8eedbd4e01dd22f8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BetterBiomes-Fabric-1.1.4.3-1.20.2-sources.jar",
          "url": "BetterBiomes-Fabric-1.1.4.3-1.20.2-sources.jar",
          "size": 169098,
          "sha512": "1b7c5b681aba0ccd1cebb930fd36e62665d0fa770b4afa62439a3a080f9ca83e260f283fe61b43dc6960cf82a77fe3f2b498a7c26bab52bf8ff9415b3f63e2d3",
          "sha256": "5f21eeec45015366e9c8ed530350171c84d1e5435493d2ec50b6f7bf33e85c20",
          "sha1": "cbd3d1a028b9500444495ec0825834c7ef0b93f8",
          "md5": "e5a1f87b127e984cbe5e634f82ea21ca"
        }
      ]
    }
  ]
}
