{
  "formatVersion": "1.1",
  "component": {
    "group": "net.crypticverse.betterbiomes",
    "module": "BetterBiomes-Fabric",
    "version": "2.1.5.2-1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "13.0.121"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "11.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "BetterBiomes-Fabric-2.1.5.2-1.20.4.jar",
          "url": "BetterBiomes-Fabric-2.1.5.2-1.20.4.jar",
          "size": 2896984,
          "sha512": "4951464f6260165235e3256c562fb34fc1529da637439fa367f0bb17fe431c3c7f44032e12a0846f78cb60910fa4f84005547c6b6805d531fb49b72856178ed0",
          "sha256": "d0ca5944195c673d4babad72c3628ee89e6bcea424d07ebe23a1531104c34b51",
          "sha1": "182a9d722431d9f6ba990cc2ca5d09e9f7ace4f5",
          "md5": "5ab9c28d87dade963a8223c08423e198"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "13.0.121"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "11.0.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "com.bookkeepersmc",
          "module": "Notebook-api-fabric-1.20.4",
          "version": {
            "requires": "1.1.10+1.20.4"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.4-3.3.0.12"
          }
        },
        {
          "group": "com.terraformersmc.terraform-api",
          "module": "terraform-wood-api-v1",
          "version": {
            "requires": "9.0.0"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "14.0.688"
          }
        }
      ],
      "files": [
        {
          "name": "BetterBiomes-Fabric-2.1.5.2-1.20.4.jar",
          "url": "BetterBiomes-Fabric-2.1.5.2-1.20.4.jar",
          "size": 2896984,
          "sha512": "4951464f6260165235e3256c562fb34fc1529da637439fa367f0bb17fe431c3c7f44032e12a0846f78cb60910fa4f84005547c6b6805d531fb49b72856178ed0",
          "sha256": "d0ca5944195c673d4babad72c3628ee89e6bcea424d07ebe23a1531104c34b51",
          "sha1": "182a9d722431d9f6ba990cc2ca5d09e9f7ace4f5",
          "md5": "5ab9c28d87dade963a8223c08423e198"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BetterBiomes-Fabric-2.1.5.2-1.20.4-sources.jar",
          "url": "BetterBiomes-Fabric-2.1.5.2-1.20.4-sources.jar",
          "size": 241215,
          "sha512": "efed5176571d537052fbfa99fc23075dba5847770192d7a42f879d5c7a31cf4de90b659834c7c71c7d5aae64b6fd2d8fbc075d06be10ba4eb3d500563613fb6b",
          "sha256": "47515859de9e2b6b162bc595e2ace7f79411ef1ba03a0517166bb2d28a7d6d41",
          "sha1": "dcf1f0b69d3c9e2a9213fd0149f6d52884a99ccf",
          "md5": "7949a10924ef1d41e7eadb3073333452"
        }
      ]
    }
  ]
}
