{
  "formatVersion": "1.1",
  "component": {
    "group": "net.crypticverse.betterbiomes",
    "module": "BetterBiomes-Fabric",
    "version": "2.1.3.3-1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "13.0.114"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "11.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "BetterBiomes-Fabric-2.1.3.3-1.20.4.jar",
          "url": "BetterBiomes-Fabric-2.1.3.3-1.20.4.jar",
          "size": 2632414,
          "sha512": "a0b4d378560aa7a4e468ef3dc2c47e225d87c4b69846583c729ce951b60f576f1bf353cbaa65a64cfdf8ec65508b6493c055a8c09259e9bc0d5461a70daed15f",
          "sha256": "714301d2d2dc97728d55b58415ce73f064b7f987b08bf52dc73e8a87a2f05380",
          "sha1": "b2525c106fb18037e807791085dab9a92cdcef05",
          "md5": "b8fa124572d48825ea1ae7edf6ba16c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "13.0.114"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "11.0.8"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.91.3+1.20.4"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.4-3.3.0.4"
          }
        },
        {
          "group": "com.terraformersmc.terraform-api",
          "module": "terraform-wood-api-v1",
          "version": {
            "requires": "9.0.0-beta.2"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "14.0.687"
          }
        }
      ],
      "files": [
        {
          "name": "BetterBiomes-Fabric-2.1.3.3-1.20.4.jar",
          "url": "BetterBiomes-Fabric-2.1.3.3-1.20.4.jar",
          "size": 2632414,
          "sha512": "a0b4d378560aa7a4e468ef3dc2c47e225d87c4b69846583c729ce951b60f576f1bf353cbaa65a64cfdf8ec65508b6493c055a8c09259e9bc0d5461a70daed15f",
          "sha256": "714301d2d2dc97728d55b58415ce73f064b7f987b08bf52dc73e8a87a2f05380",
          "sha1": "b2525c106fb18037e807791085dab9a92cdcef05",
          "md5": "b8fa124572d48825ea1ae7edf6ba16c3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BetterBiomes-Fabric-2.1.3.3-1.20.4-sources.jar",
          "url": "BetterBiomes-Fabric-2.1.3.3-1.20.4-sources.jar",
          "size": 163274,
          "sha512": "6aa74e8737039c77eab0d8c94518fec5efa21a786c521724aa8f5994fbdce47928b223069d1069eeb06da34601f4ae1d0277136e282447d20f14a0fc9e34a3f0",
          "sha256": "8911ce39b2e8053e41abd4ceb015d69cd65e8caffbde76acd7a5640100b6863a",
          "sha1": "56f4285109156dce4b181542773a3e160a66b84c",
          "md5": "d619cbe47038631de4b1d36bf5aa45ec"
        }
      ]
    }
  ]
}
