{
  "formatVersion": "1.1",
  "component": {
    "group": "net.crypticverse.betterbiomes",
    "module": "BetterBiomes-Fabric",
    "version": "2.1.4.1-1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "13.0.121"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "11.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "BetterBiomes-Fabric-2.1.4.1-1.20.4.jar",
          "url": "BetterBiomes-Fabric-2.1.4.1-1.20.4.jar",
          "size": 2639568,
          "sha512": "db16ac7e408297cad823a2cae3a6299c31a2f8b29a4599433ef678b4d4c5b2e42fdbf0760d48ae0fc594609976622c6851e57eddda8bad37e9c33a893893019d",
          "sha256": "cef57c84762f473153bcd76b0f0a038da1c6ceb3fbfc3c7f3ef313a1e44af20e",
          "sha1": "17e56d22172f39f2fe8e3f3a6b398516e513dafb",
          "md5": "6755f49c494273f3dee9513155beaac6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "13.0.121"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "11.0.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.1+1.20.4"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.4-3.3.0.5"
          }
        },
        {
          "group": "com.terraformersmc.terraform-api",
          "module": "terraform-wood-api-v1",
          "version": {
            "requires": "9.0.0"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "14.0.688"
          }
        }
      ],
      "files": [
        {
          "name": "BetterBiomes-Fabric-2.1.4.1-1.20.4.jar",
          "url": "BetterBiomes-Fabric-2.1.4.1-1.20.4.jar",
          "size": 2639568,
          "sha512": "db16ac7e408297cad823a2cae3a6299c31a2f8b29a4599433ef678b4d4c5b2e42fdbf0760d48ae0fc594609976622c6851e57eddda8bad37e9c33a893893019d",
          "sha256": "cef57c84762f473153bcd76b0f0a038da1c6ceb3fbfc3c7f3ef313a1e44af20e",
          "sha1": "17e56d22172f39f2fe8e3f3a6b398516e513dafb",
          "md5": "6755f49c494273f3dee9513155beaac6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BetterBiomes-Fabric-2.1.4.1-1.20.4-sources.jar",
          "url": "BetterBiomes-Fabric-2.1.4.1-1.20.4-sources.jar",
          "size": 168409,
          "sha512": "70167704354d74c0b85553cfeecbeb05bc515c5ea58bf5a0579c46d5431dfc44c5f0c9840b258f64255c6f3b10c059a536b347d9ec62d4269f24d5b0f3f996bc",
          "sha256": "39f3865227745c595581d2aec692e35f0e6767664c22b719c9cc5bc84c551055",
          "sha1": "bdd71886a60478b731ff340f9ee134ff0e9d2e2f",
          "md5": "e438625c7009975fa13c96855602cd72"
        }
      ]
    }
  ]
}
