{
  "formatVersion": "1.1",
  "component": {
    "group": "net.crypticverse.betterbiomes",
    "module": "BetterBiomes-Fabric",
    "version": "2.1.4.5-1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "13.0.121"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "11.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "BetterBiomes-Fabric-2.1.4.5-1.20.4.jar",
          "url": "BetterBiomes-Fabric-2.1.4.5-1.20.4.jar",
          "size": 2774107,
          "sha512": "c5449a71e0c472342a3b9fddfaa80c2b6bc8de1d01de1dbc0bfd9a1184b65809ab6a3ec647f1804dad14cb191ec0fb997c3d44a37c872c11fe2776d9d402e56b",
          "sha256": "15294a168e47ef121ef46e4301bee0d45a6b357b16aaada18d0e1752f1f041ea",
          "sha1": "037119d75131ba5bae286e7fe654921080a3cfeb",
          "md5": "d6a2cb0da78e9b144dd4f4f0c2bb78c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "13.0.121"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "11.0.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.95.0+1.20.4"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.4-3.3.0.10"
          }
        },
        {
          "group": "com.terraformersmc.terraform-api",
          "module": "terraform-wood-api-v1",
          "version": {
            "requires": "9.0.0"
          }
        },
        {
          "group": "net.crypticverse.secret",
          "module": "BetterBiomes-Secret",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "14.0.688"
          }
        }
      ],
      "files": [
        {
          "name": "BetterBiomes-Fabric-2.1.4.5-1.20.4.jar",
          "url": "BetterBiomes-Fabric-2.1.4.5-1.20.4.jar",
          "size": 2774107,
          "sha512": "c5449a71e0c472342a3b9fddfaa80c2b6bc8de1d01de1dbc0bfd9a1184b65809ab6a3ec647f1804dad14cb191ec0fb997c3d44a37c872c11fe2776d9d402e56b",
          "sha256": "15294a168e47ef121ef46e4301bee0d45a6b357b16aaada18d0e1752f1f041ea",
          "sha1": "037119d75131ba5bae286e7fe654921080a3cfeb",
          "md5": "d6a2cb0da78e9b144dd4f4f0c2bb78c4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BetterBiomes-Fabric-2.1.4.5-1.20.4-sources.jar",
          "url": "BetterBiomes-Fabric-2.1.4.5-1.20.4-sources.jar",
          "size": 236188,
          "sha512": "41d0c1318b60bfd43083e475c1649f8af8295a37f856eeacd899693f8934fae322c6e63b6434a2d726adde19273f4c06007188299988654c5e1f9ff121f1a87c",
          "sha256": "3b240d7738464ef5a52b93eba6120f5132366d25e8a7501340b16132f51bbcc1",
          "sha1": "b064ccc7b08b6c4a75aba1b867bb232d78febbf8",
          "md5": "cfb8e666569cc22c982a8eeed87e3820"
        }
      ]
    }
  ]
}
